feat: Certificate completion page
uwblueprint/headsupguys pull request #102
Opened 2022-04-26 18:59 UTC by chamod-gamage

## Notion ticket link

[Certificates: End of Module Page](https://www.notion.so/uwblueprintexecs/Certificates-End-of-Module-Page-f378628b944e45eaaeee37937d223a3e)

## Implementation description
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41309709/165371323-a46f311f-c039-4915-8179-b899ed2aec78.png">

* Implements the `certificate/[toolId]` page, uses dynamic data
* Hooks up the following buttons/links
  * Toolkit > Tool breadcrumb
  * Exit and Save Progress
  * Download
  * Back to Toolkit
  * Remaining button: Share
* Adds top bar (with HUG logo linked to home) to Module page and this certificate page
* Final slide ('next' button forced to 'finish') links to Certificate page

https://www.loom.com/share/e26f328b6b374d228b14f5c44ee2c705

## Steps to test
1. Update the variable baseUrl to "http://localhost:3000/" wherever found in your editor
2. Visit http://localhost:3000/
3. Ensure you are logged in, if not log in at http://localhost:3000/login
4. Ensure a tool with a module exists, if not create one at http://localhost:3000/admin/dashboard/modules
5. Click into a module and go to final slide
6. Click Finish, check if the certificate page pops up with correct info
7. Test the buttons listed above, see if they work as intended

## What should reviewers focus on?
* Make sure the page is styled correctly and functional in terms of its buttons

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-05-06 02:19 UTC, mkanoria approved these changes
Looks great, the demo is amazing!

2022-05-06 02:19 UTC, mkanoria commented on pages/certificate/[tool].tsx
> +            setUser(currentUser);
Wonder if `setUser(await Auth.currentAuthenticatedUser())` would work? Not a big difference tho haha

2022-05-07 23:28 UTC, tawnyzhao requested changes

2022-05-07 23:28 UTC, tawnyzhao commented on pages/certificate/[tool].tsx
> +                                    <Button
Setting this button to loading while the data is fetching will avoid a default pdf from being generated

2022-06-07 01:37 UTC, chamod-gamage commented
Note that the Share button has been hidden in the recent commits.

2022-06-08 01:41 UTC, merged