[Module Builder] - Preview Screen
uwblueprint/headsupguys pull request #39
Opened 2021-08-10 16:28 UTC by christineNg1028

## Notion ticket link

[Module Builder - Preview Screen](https://www.notion.so/uwblueprintexecs/Preview-Screen-9c29f26880e84f2d94f9edaa9b60deeb)

## Implementation description
* Preview screen for module builder, mobile and desktop versions
* Props to determine buttons, button text, and progress, takes all preview content as children
* Print/save buttons disappear when false, prev/next buttons disable when false
* Modified progress bar styling

## Steps to test
1. Ensure consistent with mockups and that all functionality is included

**Usage**
![Screenshot 2021-08-10 121355](https://user-images.githubusercontent.com/69013315/128896080-65d3e621-751b-4527-97ff-9ccad94d0d8d.jpg)
Set props and pass in any content as children

**Desktop**
![Screenshot 2021-08-10 121429](https://user-images.githubusercontent.com/69013315/128896144-5cc37f30-71a0-4f20-bcfd-15ea76194752.jpg)
Note: must scroll to see buttons when content overflows

**Mobile**
![Screenshot 2021-08-10 121513](https://user-images.githubusercontent.com/69013315/128896270-c70b5b9c-6160-4eb7-acd7-4ccbdbd6d8fa.jpg)
Note: buttons fixed to bottom when content doesn't overflow

## What should reviewers focus on?
* Styling may need updates

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-08-16 17:52 UTC, nimwijetunga reviewed
Mostly looks good! However, for some reason the progress bar doesn't display for me (on Mac). This is how i render the component:
```
<ModulePreview previous={true} next={true} save={false} print={true} variant={"mobile"} progressValue={40}>
                <Button>test</Button>
                <Button>test2</Button>
                <Button>test3</Button>
            </ModulePreview>
```

2021-09-12 20:20 UTC, tawnyzhao requested changes

2021-09-12 20:20 UTC, tawnyzhao commented on src/components/modulePreview/index.tsx
> +import { Button } from "..";
This import is wrong, should be from chakra-ui

2021-09-12 20:20 UTC, tawnyzhao commented on src/definitions/chakra/theme/components/button.ts
> +        }
lint: add a comma

2021-09-12 21:06 UTC, tawnyzhao approved these changes
👍🏻

2021-09-12 21:21 UTC, chamod-gamage approved these changes
LGTM! Great work~

2021-09-12 21:37 UTC, merged