Fix/add updated at to tool schema and refactor seeding script
uwblueprint/headsupguys pull request #50
Opened 2021-09-25 16:28 UTC by NirmalHegde

## Notion ticket link
[Ticket Name](https://uwblueprintexecs.notion.site/Refactor-seeding-script-to-use-Mongoose-7b6c62965283461bb7fe58a1d40bf883)

LINKED TO BUG: https://uwblueprintexecs.notion.site/Add-updatedAt-field-to-Tool-Schema-aa56d53fcec8466e8c269246d06027b3

## Implementation description
* Refactored MongoDB seeding script to implement Mongoose, allowing for updatedAt parameter to successfully appear.
* Implemented new updatedAt parameter in tools

## Steps to test
1. Run `yarn seed` in terminal to see if MongoDB successfully seeds with updatedAt parameter
2. Check endpoint `admin/dashboard/tools` to see if creating a new tool gives a correct date parameter at bottom right

## What should reviewers focus on?
* Ensuring seeding script still works as intended for both `yarn seed` and `yarn seed --init`

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-09-25 18:19 UTC, yashgajaria approved these changes
Everything seems to be working as expected and looks good!

2021-09-29 00:01 UTC, chamod-gamage requested changes

2021-09-29 00:01 UTC, NirmalHegde commented on database/scripts/seed.ts
> +        })
sounds good

2021-09-29 00:01 UTC, chamod-gamage approved these changes

2021-09-29 00:02 UTC, merged