Percentage based padding
uwblueprint/headsupguys pull request #71
Opened 2022-01-22 00:44 UTC by chamod-gamage

* Implements percent based padding option
* Just play around with it and see if u like it

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-01-22 16:21 UTC, ChinemeremChigbo commented
Sweet! Looks great to me :))

2022-01-22 17:33 UTC, ChinemeremChigbo approved these changes

2022-01-23 18:15 UTC, tawnyzhao approved these changes
Added a suggestion

2022-01-23 18:15 UTC, tawnyzhao commented on database/models/section.ts
> +    percent = "percent",
Rather than using "percent" use "%" that way we can use the variable directly when referencing on the front end

2022-01-23 18:15 UTC, tawnyzhao commented on database/models/section.ts
> +                enum: ["px", "percent"],
Change "percent" use "%

2022-01-23 18:15 UTC, tawnyzhao commented on src/pages/module-builder/Document.tsx
> +                                section?.padding.type === "px" ? "px" : "%";
instead of coercing here, we can use type directly

2022-01-23 18:15 UTC, tawnyzhao commented on src/pages/module-builder/Document.tsx
> +                                    paddingTop={`${section.padding.top}${paddingType}`}
e.g `${section?.padding.type}`

2022-01-23 19:15 UTC, ChinemeremChigbo requested changes
Not sure if this is just on my end, but I just noticed that when I put in padding then change the text, the padding changes disappear, not sure if these persistence is absolutely necessary or just a nice to have, if the latter, please let me know and I'll reapprove.

2022-01-23 21:06 UTC, chamod-gamage commented
Really good catch @ChinemeremChigbo 
I added an aggregation @tawnyzhao , I'm not sure if there's libraries we can use to autorun these like pg migrations and I didn't include a reversal either but should be okay regardless. Just need to get all devs as well as someone connected to the prod db to hit `api/addPaddingTypeToSectionPadding`

2022-01-24 01:06 UTC, ChinemeremChigbo approved these changes
Persistent data! Nice.

2022-01-24 01:24 UTC, merged