(api/tool/update) Properly handle duplicates
uwblueprint/headsupguys pull request #75
Opened 2022-01-22 20:45 UTC by chamod-gamage

## Notion ticket link

[Tool Linked Module Duplicate Check Fix](https://www.notion.so/uwblueprintexecs/Task-Board-485f846ae00243599dddba2be9bcba82?p=7a2bd73d0d324ac7be3bacb7c73589d5)
(S/o to @ChinemeremChigbo for finding this bug!)

## Implementation description
* Don't throw an error on tool update if the linked module's current toolId is that of the tool being updated
* Nullifies toolId property for any other modules currently linked to the tool being updated

## Steps to test
1. Create a tool and repeatedly update, sometimes changing linked module and sometimes not

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-01-22 21:36 UTC, ChinemeremChigbo commented
The change to the update function makes it impossible to add new tools. This is due to this line:
        const existingModules = await Module.find({
            toolID: id,
            _id: { $ne: tool.linkedModuleID },
        });

consider changing the find function to work slightly differently

2022-01-22 21:36 UTC, ChinemeremChigbo requested changes
See comment

2022-01-22 22:09 UTC, chamod-gamage commented
> The change to the update function makes it impossible to add new tools. This is due to this line: const existingModules = await Module.find({ toolID: id, _id: { $ne: tool.linkedModuleID }, });
> 
> consider changing the find function to work slightly differently

Good catch! Added a check to see if the tool has a linkedModuleId to determine whether to include it in the find query params

2022-01-22 22:20 UTC, ChinemeremChigbo commented
Nice!

2022-01-22 22:20 UTC, ChinemeremChigbo approved these changes
Nice!

2022-01-27 22:56 UTC, tawnyzhao approved these changes

2022-01-27 23:39 UTC, merged